version: '3'

services:
  api:
    build:
      context: .
    container_name: api
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    env_file:
      .env
    volumes:
#      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    restart: always
    image: postgres:12-alpine
    container_name: api-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bb
    ports:
      - 5433:5432
    volumes:
      - ./scripts/db:/scripts
      - ./dockerDB/api:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5



