export enum DeliveryStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  ENROUTE_PICKUP = 'ENROUTE_PICKUP ',
  DELAYED = 'DELAYED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DELIVERED = 'DELIVERED',
  PARTIAL_DELIVERY = 'PARTIAL_DELIVERY',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}
